name: Research
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - flake8
  - ipython
  - jupyter
  - matplotlib
  - numpy
  - pyflakes
  - pylint
  - pytest
  - scipy
  - pyyaml
  - jupyterlab
  - ipdb
