# default parameter values
time_final: 0.33 # final time
delta_t: 0.02 # constant time step

is_weak: True # switch between weak and strong formulations

use_wave_propogation_method: False # Use WPM with fluctuations as a FV method

basis:
    basis_class: legendre_2d_cartesian
    space_order: 1
    inner_product_constant: 0.25 # constant weighting on orthogonality condition

mesh:
    mesh_class: mesh_2d_cartesian
    x_left: 0.0 
    x_right: 1.0 
    y_bottom: 0.0 
    y_top: 1.0
    num_rows: 10
    num_cols: 10

boundary_condition:
    boundary_condition_class: periodic # option periodic, dirichlet, neumann, extrapolation, interior

riemann_solver:
    riemann_solver_class: local_lax_friedrichs # many options, see riemann_solvers.py

fluctuation_solver:
    fluctuation_solver_class: roe # fluctuation solver

time_stepping:
    time_stepping_class: explicit_runge_kutta
    order: 1
    num_frames: 10
    is_adaptive_time_stepping: False
    is_verbose: True

shock_capturing_limiter:
    shock_capturing_limiter_class: # options (empty/None), bounds, moment
    bounds_alpha_value: 50 # number greater than 0, 50 is default
    # list of points on [-1, 1] such as [-1.0, 0.0, 1.0], where to check for min/max
    bounds_points: # empty parameter gives default of 5 Gauss-Lobatto points

positivity_preserving_limiter:
    positivity_preserving_limiter_class: # options (empty means None), shu_osher
