time_final: 0.1 # final time
delta_t: 0.01 # constant time step

is_weak: True # switch between weak and strong formulations

basis:
    basis_class: modal_2d_triangle # options nodal, gauss_lobatto, gauss_legendre, legendre
    # legendre modal basis
    space_order: 1
    inner_product_constant: 0.5 # constant weighting on orthogonality condition

mesh:
    mesh_class: mesh_2d_triangulated_rectangle
    x_left: 0.0
    x_right: 1.0
    y_bottom: 0.0
    y_top: 1.0
    num_rows: 2
    num_cols: 2

boundary_condition:
    boundary_condition_class: dirichlet # option periodic, dirichlet, neumann, extrapolation, interior

riemann_solver:
    riemann_solver_class: local_lax_friedrichs # many options, see riemann_solvers.py

time_stepping:
    time_stepping_class: explicit_runge_kutta
    order: 1
    num_frames: 10
    is_adaptive_time_stepping: False
    is_verbose: True
