### definitions ###

# default/library definitions
include $(MESHGEN_DOGPACK)/lib/Makefile.defs

# compiler options
#
# overridden library objects
#
SignedDistance = SignedDistance
MeshSpacing    = MeshSpacing

# place to add object modules
#
ALL_OBJECTS = $(COMMON_OBJECTS) \

ALL_SOURCES = $(COMMON_SOURCES) \

### targets ###

include $(MESHGEN_DOGPACK)/lib/Makefile.targets

### DO NOT remove this line - make depends on it ###
