# default parameter values
time_final: 1.0 # final time
delta_t: 0.1 # constant time step

is_weak: True # switch between weak and strong formulations

use_wave_propagation_method: False # Use WPM with fluctuations as a FV method

basis:
    basis_class: legendre # options nodal, gauss_lobatto, gauss_legendre, legendre, finite_volume
    # legendre modal basis
    num_basis_cpts: 1
    inner_product_constant: 0.5 # constant weighting on orthogonality condition

mesh:
    mesh_class: mesh_1d_uniform # or mesh_1d for unstructured, mesh_2d_cartesian
    num_elems: 10 # number of elements
    x_left: 0.0 # left boundary
    x_right: 1.0 # right boundary
    vertices: [0.0, 0.5, 1.0] # vertices for 1d unstructured mesh

boundary_condition:
    boundary_condition_class: periodic # option periodic, dirichlet, neumann, extrapolation, interior

riemann_solver:
    riemann_solver_class: local_lax_friedrichs # many options, see riemann_solvers.py

time_stepping:
    time_stepping_class: explicit_runge_kutta
    order: 1
    num_frames: 10
    is_adaptive_time_stepping: False
    is_verbose: True

shock_capturing_limiter:
    shock_capturing_limiter_class: # options (empty/None), bounds, moment
    bounds_alpha_value: 50 # number greater than 0, 50 is default
    # list of points on [-1, 1] such as [-1.0, 0.0, 1.0], where to check for min/max
    bounds_points: # empty parameter gives default of 5 Gauss-Lobatto points

positivity_preserving_limiter:
    positivity_preserving_limiter_class: # options (empty means None), shu_osher
